-- MySQL Script generated by MySQL Workbench
-- Сб 25 апр 2020 16:15:49
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema restaurantdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema restaurantdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `restaurantdb` DEFAULT CHARACTER SET utf8 ;
USE `restaurantdb` ;

-- -----------------------------------------------------
-- Table `restaurantdb`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `restaurantdb`.`role` ;

CREATE TABLE IF NOT EXISTS `restaurantdb`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `restaurantdb`.`user_address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `restaurantdb`.`user_address` ;

CREATE TABLE IF NOT EXISTS `restaurantdb`.`user_address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(64) NOT NULL,
  `street` VARCHAR(64) NOT NULL,
  `house` VARCHAR(45) NOT NULL,
  `apartment` VARCHAR(45) NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `restaurantdb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `restaurantdb`.`user` ;

CREATE TABLE IF NOT EXISTS `restaurantdb`.`user` (
  `email` VARCHAR(64) NOT NULL,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `surename` VARCHAR(45) NULL,
  `age` INT NULL,
  `password` VARCHAR(512) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `verified` TINYINT NOT NULL,
  `enable` TINYINT NOT NULL,
  `role_id` INT NOT NULL DEFAULT 1,
  `user_address_id` INT NULL,
  PRIMARY KEY (`email`),
  INDEX `fk_user_role1_idx` (`role_id` ASC) VISIBLE,
  INDEX `fk_user_user_address1_idx` (`user_address_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `restaurantdb`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_user_address1`
    FOREIGN KEY (`user_address_id`)
    REFERENCES `restaurantdb`.`user_address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `restaurantdb`.`email_token`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `restaurantdb`.`email_token` ;

CREATE TABLE IF NOT EXISTS `restaurantdb`.`email_token` (
  `user_email` VARCHAR(64) NOT NULL,
  `token` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`user_email`),
  UNIQUE INDEX `token_UNIQUE` (`token` ASC) VISIBLE,
  CONSTRAINT `fk_email_token_user`
    FOREIGN KEY (`user_email`)
    REFERENCES `restaurantdb`.`user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `restaurantdb`.`restaurant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `restaurantdb`.`restaurant` ;

CREATE TABLE IF NOT EXISTS `restaurantdb`.`restaurant` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `tiny_description` VARCHAR(256) NOT NULL,
  `description` TEXT NOT NULL,
  `phone` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `restaurantdb`.`restaurant_legal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `restaurantdb`.`restaurant_legal` ;

CREATE TABLE IF NOT EXISTS `restaurantdb`.`restaurant_legal` (
  `restaurant_id` INT NOT NULL,
  `ogrn` VARCHAR(13) NOT NULL,
  `legal_name` VARCHAR(128) NOT NULL,
  `inn` VARCHAR(12) NOT NULL,
  `address` TEXT NOT NULL,
  PRIMARY KEY (`restaurant_id`),
  CONSTRAINT `fk_restaurant_legal_restaurant1`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `restaurantdb`.`restaurant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `restaurantdb`.`branch`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `restaurantdb`.`branch` ;

CREATE TABLE IF NOT EXISTS `restaurantdb`.`branch` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `restaurant_id` INT NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `address` TEXT NOT NULL,
  `enable` TINYINT NOT NULL,
  INDEX `fk_branch_restaurant1_idx` (`restaurant_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_branch_restaurant1`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `restaurantdb`.`restaurant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `restaurantdb`.`promo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `restaurantdb`.`promo` ;

CREATE TABLE IF NOT EXISTS `restaurantdb`.`promo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `discount` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `restaurantdb`.`menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `restaurantdb`.`menu` ;

CREATE TABLE IF NOT EXISTS `restaurantdb`.`menu` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `branch_id` INT NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `weight` FLOAT NOT NULL,
  `composition` TEXT NOT NULL,
  `price` INT NOT NULL,
  `enable` TINYINT NOT NULL,
  `promo_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ingredient_branch1_idx` (`branch_id` ASC) VISIBLE,
  INDEX `fk_menu_promo1_idx` (`promo_id` ASC) VISIBLE,
  CONSTRAINT `fk_ingredient_branch1`
    FOREIGN KEY (`branch_id`)
    REFERENCES `restaurantdb`.`branch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_menu_promo1`
    FOREIGN KEY (`promo_id`)
    REFERENCES `restaurantdb`.`promo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `restaurantdb`.`staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `restaurantdb`.`staff` ;

CREATE TABLE IF NOT EXISTS `restaurantdb`.`staff` (
  `id` INT NOT NULL,
  `branch_id` INT NOT NULL,
  `user_email` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_staff_branch1_idx` (`branch_id` ASC) VISIBLE,
  INDEX `fk_staff_user1_idx` (`user_email` ASC) VISIBLE,
  CONSTRAINT `fk_staff_branch1`
    FOREIGN KEY (`branch_id`)
    REFERENCES `restaurantdb`.`branch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_staff_user1`
    FOREIGN KEY (`user_email`)
    REFERENCES `restaurantdb`.`user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `restaurantdb`.`restaurant_secret`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `restaurantdb`.`restaurant_secret` ;

CREATE TABLE IF NOT EXISTS `restaurantdb`.`restaurant_secret` (
  `restaurant_id` INT NOT NULL,
  `token` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`restaurant_id`),
  CONSTRAINT `fk_restaurant_secret_restaurant1`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `restaurantdb`.`restaurant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `restaurantdb`.`branch_secret`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `restaurantdb`.`branch_secret` ;

CREATE TABLE IF NOT EXISTS `restaurantdb`.`branch_secret` (
  `branch_id` INT NOT NULL,
  `token` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`branch_id`),
  CONSTRAINT `fk_branch_secret_branch1`
    FOREIGN KEY (`branch_id`)
    REFERENCES `restaurantdb`.`branch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `restaurantdb`.`branch_seat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `restaurantdb`.`branch_seat` ;

CREATE TABLE IF NOT EXISTS `restaurantdb`.`branch_seat` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `branch_id` INT NOT NULL,
  `num` INT NOT NULL,
  `table_num` INT NOT NULL,
  `enable` TINYINT NOT NULL,
  `user_email` VARCHAR(64) NULL,
  `staff_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_branch_seat_branch1_idx` (`branch_id` ASC) VISIBLE,
  INDEX `fk_branch_seat_user1_idx` (`user_email` ASC) VISIBLE,
  INDEX `fk_branch_seat_staff1_idx` (`staff_id` ASC) VISIBLE,
  CONSTRAINT `fk_branch_seat_branch1`
    FOREIGN KEY (`branch_id`)
    REFERENCES `restaurantdb`.`branch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_branch_seat_user1`
    FOREIGN KEY (`user_email`)
    REFERENCES `restaurantdb`.`user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_branch_seat_staff1`
    FOREIGN KEY (`staff_id`)
    REFERENCES `restaurantdb`.`staff` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `restaurantdb`.`order_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `restaurantdb`.`order_status` ;

CREATE TABLE IF NOT EXISTS `restaurantdb`.`order_status` (
  `id` INT NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `restaurantdb`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `restaurantdb`.`order` ;

CREATE TABLE IF NOT EXISTS `restaurantdb`.`order` (
  `id` INT NOT NULL,
  `price` INT NOT NULL DEFAULT 0,
  `order_date` DATETIME NOT NULL,
  `user_email` VARCHAR(64) NOT NULL,
  `order_status_id` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_order_user1_idx` (`user_email` ASC) VISIBLE,
  INDEX `fk_order_order_status1_idx` (`order_status_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_user1`
    FOREIGN KEY (`user_email`)
    REFERENCES `restaurantdb`.`user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_order_status1`
    FOREIGN KEY (`order_status_id`)
    REFERENCES `restaurantdb`.`order_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `restaurantdb`.`user_menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `restaurantdb`.`user_menu` ;

CREATE TABLE IF NOT EXISTS `restaurantdb`.`user_menu` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `branch_seat_id` INT NOT NULL,
  `menu_id` INT NOT NULL,
  `item_count` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cart_branch_seat1_idx` (`branch_seat_id` ASC) VISIBLE,
  INDEX `fk_cart_menu1_idx` (`menu_id` ASC) VISIBLE,
  INDEX `fk_user_menu_order1_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `fk_cart_branch_seat1`
    FOREIGN KEY (`branch_seat_id`)
    REFERENCES `restaurantdb`.`branch_seat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cart_menu1`
    FOREIGN KEY (`menu_id`)
    REFERENCES `restaurantdb`.`menu` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_menu_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `restaurantdb`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
